version: "2.0"
services:
  #PHP Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: db_mysql
      DB_USERNAME: user
      DB_PASSWORD: secret
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network
    ports:
      - "9000:9000"

  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ../frontend:/var/www/
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: db_mysql
        MYSQL_USER: user
        MYSQL_PASSWORD: secret
    ports:
        - "3306:3306"
    volumes:
        - db-data:/var/lib/mysql
    networks:
        - app-network

  #Nginx Service
  webserver:
    depends_on:
      - backend
      - frontend
      - db
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
    db-data:
